Django framwork/django-begin/book/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    # path('', views.index, name='index'),
    path('', login_required(views.BookListView.as_view(), login_url='/login'), name='index'),
    # path('detail/<slug:slug>/', views.detail, name='detail'),
    path('detail/<slug:slug>/', views.BookDetailView.as_view(), name='detail'),
    re_path(r'add/$', views.book_add, name='book_add'),

    re_path(r'cart/add/(?P<slug>[\w-]+)/$', views.cart_add, name='cart_add'),
    re_path(r'cart/delete/(?P<slug>[\w-]+)/$', views.cart_delete, name='cart_delete'),
    re_path(r'cart/checkout/$', views.cart_checkout, name='cart_checkout')
 
]

Django framwork/django-begin/myapp/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
     path('signup/', views.signup_view, name='signup'),
    path('hello/<int:id>', views.hello, name='hello'),
    re_path(r'article/(?P<year>[0-9]{4})/(?P<slug>[\w-]+)/$', views.article, name='article'),
]

Django framwork/django-begin/testproject/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from book.api import router

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('', include(('myapp.urls','myapp') , namespace='myapp')),
    path('book/', include(('book.urls','book') , namespace='book')),
 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django framwork/django-begin/templates/index.html
{% extends "layouts/base.html" %}

{% block title %} Index Page {% endblock%}

{% block content %}
<h1>Hello Index Page</h1>
<h2>{{ id }}</h2>
<h2>{{ name }}</h2>
<h2>{{ email }}</h2>

{% if id == '001' and name == 'Vick' %}
<h2>Access OK!</h2>
{% else %}
<h2>Access Error!</h2>
{% endif %}

<ul>
{% for x in activities %}

<li>{{ x }}</li>

{% endfor %}
</ul>

<a href="{% url 'myapp:index'  %}"> Go to Index Page</a><br>
<a href="{% url 'myapp:hello' id=1 %}"> Go to Hello Page</a><br>
<a href="{% url 'myapp:article' year=2020 slug='basic-python-programming' %}"> Go to Article Page</a><br>
<a href="{% url 'book:index' %}"> Go to Book Page</a><br>

{% endblock %}