Django framwork/django-begin/book/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    # path('', views.index, name='index'),
    path('', login_required(views.BookListView.as_view(), login_url='/login'), name='index'),
    # path('detail/<slug:slug>/', views.detail, name='detail'),
    path('detail/<slug:slug>/', views.BookDetailView.as_view(), name='detail'),
    re_path(r'add/$', views.book_add, name='book_add'),

    re_path(r'cart/add/(?P<slug>[\w-]+)/$', views.cart_add, name='cart_add'),
    re_path(r'cart/delete/(?P<slug>[\w-]+)/$', views.cart_delete, name='cart_delete'),
    re_path(r'cart/checkout/$', views.cart_checkout, name='cart_checkout')
 
]

Django framwork/django-begin/myapp/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
     path('signup/', views.signup_view, name='signup'),
    path('hello/<int:id>', views.hello, name='hello'),
    re_path(r'article/(?P<year>[0-9]{4})/(?P<slug>[\w-]+)/$', views.article, name='article'),
]

Django framwork/django-begin/testproject/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from book.api import router

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('', include(('myapp.urls','myapp') , namespace='myapp')),
    path('book/', include(('book.urls','book') , namespace='book')),
 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django framwork/django-begin/templates/layouts/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Test Project {% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.0/css/fontawesome.min.css"
    integrity="sha384-z4tVnCr80ZcL0iufVdGQSUzNvJsKjEtqYZjiQrrYKlpGow+btDHDfQWkFjoaz/Zr" crossorigin="anonymous">
</head>

<body>
  <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center text-dark text-decoration-none">

      <span class="fs-4">Book Store</span>
    </a>
    <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
      <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'myapp:index' %}">Home</a>
      <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'book:index' %}">Book</a>
    </nav>
    {% if request.session.cart_qty %}
    <a class="btn btn-secondary mx-2" href="{% url 'book:cart_list' %}"><i class="fa fa-shopping-cart"></i>
      {{request.session.cart_qty }}</a>
    {% endif %}
    

    {% if not user.is_authenticated %}
    <a class="btn btn-outline-primary mx-2" href="{% url 'myapp:signup' %}">Sign Up</a>
    <a class="btn btn-info mx-2" href="{% url 'myapp:login' %}">Log in</a>
    {% endif %}


    {% if user.is_authenticated %}
    <span>Hello, {{ request.user.username }}</span>
    <form method="post" action="{% url 'myapp:logout' %}" novalidate>
      {% csrf_token %}
      <button type="submit" class="btn btn-danger mx-2">Log out</button>
    </form>
    {% endif %}
  </div>
  <div class="container-fluid">

    {% if messages %}
    {% for msg in messages %}
    {% if msg.tags == 'success' %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <strong>Success</strong>{{ msg }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}

    {% if msg.tags == 'error' %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <strong>Eorror</strong>{{ msg }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% block content %}{% endblock %}

  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
    crossorigin="anonymous"></script>
</body>

</html>